### ISSUE TITLE
flutter pub get fails 

### ISSUE THREAD

**Issue by nandakav** [MarloKessler/flutter-extended_shared_preferences#2]
The plugin `extended_shared_preferences` doesn't have a main class defined in
C:\Users\avnandak.ORADEV\AppData\Roaming\hosted\pub.dartlang.org\extended_shared_preferences-1.0.0\android\src\main\java\com\connapptivity\developer\sharedpreferences\Sharedp
referencesPlugin.java or
C:\Users\avnandak.ORADEV\AppData\Roaming\hosted\pub.dartlang.org\extended_shared_preferences-1.0.0\android\src\main\kotlin\com\connapptivity\developer\sharedpreferences\Share
dpreferencesPlugin.kt. This is likely to due to an incorrect `androidPackage: com.connapptivity.developer.sharedpreferences` or `mainClass` entry in the plugin's
pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this
plugin and consider using a different plugin in the meanwhile.

in the pubspec.yaml I have 
  extended_shared_preferences: ^1.0.0

All other plugins work correctly.
Using windows X. 

Android studio 3.6.3 

flutter doctor summary. 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[!] Connected device
    ! No devices available

**Comment by marlokessler** [comment]
Hey, excuse me for my late response. As it seems, you do not use the up-to-date version of this plugin, because this error was tracked in [this issue](https://github.com/MarloKessler/flutter-extended_shared_preferences/issues/1) and was solved in the latest version. So please try running `flutter pub upgrade`/`flutter pub get` to update your packages. I will close this issue, but please feel free to open a new one, if the error keeps appearing.

**Comment by nandakav** [comment]
I believe you need to upgrade the pubspec.yaml version to 1.0.1 else the upgrade or update fails.
